#!usr/bin/env Rscript
col_names <- c("subid","pid",
#"p97_act1","p97_act2","p97_actmean","p97_rsaD","p97_rsaDBwc","p97_rsadiff",
"LVVC_act1","LVVC_act2","LVVC_actmean","LVVC_rsaD","LVVC_rsaDBwc","LVVC_rsadiff",
"LANG_act1","LANG_act2","LANG_actmean","LANG_rsaD","LANG_rsaDBwc","LANG_rsadiff",
"LSMG_act1","LSMG_act2","LSMG_actmean","LSMG_rsaD","LSMG_rsaDBwc","LSMG_rsadiff",
"LIFG_act1","LIFG_act2","LIFG_actmean","LIFG_rsaD","LIFG_rsaDBwc","LIFG_rsadiff",
"LMFG_act1","LMFG_act2","LMFG_actmean","LMFG_rsaD","LMFG_rsaDBwc","LMFG_rsadiff",
"RVVC_act1","RVVC_act2","RVVC_actmean","RVVC_rsaD","RVVC_rsaDBwc","RVVC_rsadiff",
"RANG_act1","RANG_act2","RANG_actmean","RANG_rsaD","RANG_rsaDBwc","RANG_rsadiff",
"RSMG_act1","RSMG_act2","RSMG_actmean","RSMG_rsaD","RSMG_rsaDBwc","RSMG_rsadiff",
"RIFG_act1","RIFG_act2","RIFG_actmean","RIFG_rsaD","RIFG_rsaDBwc","RIFG_rsadiff",
"RMFG_act1","RMFG_act2","RMFG_actmean","RMFG_rsaD","RMFG_rsaDBwc","RMFG_rsadiff",
"LaPHG_act1","LaPHG_act2","LaPHG_actmean","LaPHG_rsaD","LaPHG_rsaDBwc","LaPHG_rsadiff",
"LpPHG_act1","LpPHG_act2","LpPHG_actmean","LpPHG_rsaD","LpPHG_rsaDBwc","LpPHG_rsadiff",
"RaPHG_act1","RaPHG_act2","RaPHG_actmean","RaPHG_rsaD","RaPHG_rsaDBwc","RaPHG_rsadiff",
"RpPHG_act1","RpPHG_act2","RpPHG_actmean","RpPHG_rsaD","RpPHG_rsaDBwc","RpPHG_rsadiff",
"HIP_act1","HIP_act2","HIP_actmean","HIP_rsaD","HIP_rsaDBwc","HIP_rsadiff",
"CA1_act1","CA1_act2","CA1_actmean","CA1_rsaD","CA1_rsaDBwc","CA1_rsadiff",
"CA2_act1","CA2_act2","CA2_actmean","CA2_rsaD","CA2_rsaDBwc","CA2_rsadiff",
"DG_act1","DG_act2","DG_actmean","DG_rsaD","DG_rsaDBwc","DG_rsadiff",
"CA3_act1","CA3_act2","CA3_actmean","CA3_rsaD","CA3_rsaDBwc","CA3_rsadiff",
"subiculum_act1","subiculum_act2","subiculum_actmean","subiculum_rsaD","subiculum_rsaDBwc","subiculum_rsadiff",
"ERC_act1","ERC_act2","ERC_actmean","ERC_rsaD","ERC_rsaDBwc","ERC_rsadiff",
"PRC_act1","PRC_act2","PRC_actmean","PRC_rsaD","PRC_rsaDBwc","PRC_rsadiff",
"pPHG_act1","pPHG_act2","pPHG_actmean","pPHG_rsaD","pPHG_rsaDBwc","pPHG_rsadiff")
save(col_names,file=paste("col_names.Rda",sep=""))
