fsl_sub bash run_ERS.sh itemInfo_LVVC_CA1.R
fsl_sub bash run_ERS.sh itemInfo_LVVC_DG.R
fsl_sub bash run_ERS.sh itemInfo_LVVC_SUB.R
fsl_sub bash run_ERS.sh itemInfo_LVVC_ERC.R
fsl_sub bash run_ERS.sh itemInfo_RVVC_CA1.R
fsl_sub bash run_ERS.sh itemInfo_RVVC_DG.R
fsl_sub bash run_ERS.sh itemInfo_RVVC_SUB.R
fsl_sub bash run_ERS.sh itemInfo_RVVC_ERC.R
fsl_sub bash run_ERS.sh itemInfo_LIFG_CA1.R
fsl_sub bash run_ERS.sh itemInfo_LIFG_DG.R
fsl_sub bash run_ERS.sh itemInfo_LIFG_SUB.R
fsl_sub bash run_ERS.sh itemInfo_LIFG_ERC.R
fsl_sub bash run_ERS.sh itemInfo_RIFG_CA1.R
fsl_sub bash run_ERS.sh itemInfo_RIFG_DG.R
fsl_sub bash run_ERS.sh itemInfo_RIFG_SUB.R
fsl_sub bash run_ERS.sh itemInfo_RIFG_ERC.R
fsl_sub bash run_ERS.sh itemInfo_LANG_CA1.R
fsl_sub bash run_ERS.sh itemInfo_LANG_DG.R
fsl_sub bash run_ERS.sh itemInfo_LANG_SUB.R
fsl_sub bash run_ERS.sh itemInfo_LANG_ERC.R
fsl_sub bash run_ERS.sh itemInfo_RANG_CA1.R
fsl_sub bash run_ERS.sh itemInfo_RANG_DG.R
fsl_sub bash run_ERS.sh itemInfo_RANG_SUB.R
fsl_sub bash run_ERS.sh itemInfo_RANG_ERC.R
fsl_sub bash run_ERS.sh itemInfo_LSMG_CA1.R
fsl_sub bash run_ERS.sh itemInfo_LSMG_DG.R
fsl_sub bash run_ERS.sh itemInfo_LSMG_SUB.R
fsl_sub bash run_ERS.sh itemInfo_LSMG_ERC.R
fsl_sub bash run_ERS.sh itemInfo_RSMG_CA1.R
fsl_sub bash run_ERS.sh itemInfo_RSMG_DG.R
fsl_sub bash run_ERS.sh itemInfo_RSMG_SUB.R
fsl_sub bash run_ERS.sh itemInfo_RSMG_ERC.R
