fsl_sub bash run_mem.sh itemInfo_LVVC_CA1.R
fsl_sub bash run_mem.sh itemInfo_LVVC_CA2.R
fsl_sub bash run_mem.sh itemInfo_LVVC_CA3.R
fsl_sub bash run_mem.sh itemInfo_LVVC_DG.R
fsl_sub bash run_mem.sh itemInfo_LVVC_subiculum.R
fsl_sub bash run_mem.sh itemInfo_LVVC_ERC.R
fsl_sub bash run_mem.sh itemInfo_LVVC_HIP.R
fsl_sub bash run_mem.sh itemInfo_RVVC_CA1.R
fsl_sub bash run_mem.sh itemInfo_RVVC_CA2.R
fsl_sub bash run_mem.sh itemInfo_RVVC_CA3.R
fsl_sub bash run_mem.sh itemInfo_RVVC_DG.R
fsl_sub bash run_mem.sh itemInfo_RVVC_subiculum.R
fsl_sub bash run_mem.sh itemInfo_RVVC_ERC.R
fsl_sub bash run_mem.sh itemInfo_RVVC_HIP.R
fsl_sub bash run_mem.sh itemInfo_LANG_CA1.R
fsl_sub bash run_mem.sh itemInfo_LANG_CA2.R
fsl_sub bash run_mem.sh itemInfo_LANG_CA3.R
fsl_sub bash run_mem.sh itemInfo_LANG_DG.R
fsl_sub bash run_mem.sh itemInfo_LANG_subiculum.R
fsl_sub bash run_mem.sh itemInfo_LANG_ERC.R
fsl_sub bash run_mem.sh itemInfo_LANG_HIP.R
fsl_sub bash run_mem.sh itemInfo_RANG_CA1.R
fsl_sub bash run_mem.sh itemInfo_RANG_CA2.R
fsl_sub bash run_mem.sh itemInfo_RANG_CA3.R
fsl_sub bash run_mem.sh itemInfo_RANG_DG.R
fsl_sub bash run_mem.sh itemInfo_RANG_subiculum.R
fsl_sub bash run_mem.sh itemInfo_RANG_ERC.R
fsl_sub bash run_mem.sh itemInfo_RANG_HIP.R
fsl_sub bash run_mem.sh itemInfo_LSMG_CA1.R
fsl_sub bash run_mem.sh itemInfo_LSMG_CA2.R
fsl_sub bash run_mem.sh itemInfo_LSMG_CA3.R
fsl_sub bash run_mem.sh itemInfo_LSMG_DG.R
fsl_sub bash run_mem.sh itemInfo_LSMG_subiculum.R
fsl_sub bash run_mem.sh itemInfo_LSMG_ERC.R
fsl_sub bash run_mem.sh itemInfo_LSMG_HIP.R
fsl_sub bash run_mem.sh itemInfo_RSMG_CA1.R
fsl_sub bash run_mem.sh itemInfo_RSMG_CA2.R
fsl_sub bash run_mem.sh itemInfo_RSMG_CA3.R
fsl_sub bash run_mem.sh itemInfo_RSMG_DG.R
fsl_sub bash run_mem.sh itemInfo_RSMG_subiculum.R
fsl_sub bash run_mem.sh itemInfo_RSMG_ERC.R
fsl_sub bash run_mem.sh itemInfo_RSMG_HIP.R
fsl_sub bash run_mem.sh itemInfo_LIFG_CA1.R
fsl_sub bash run_mem.sh itemInfo_LIFG_CA2.R
fsl_sub bash run_mem.sh itemInfo_LIFG_CA3.R
fsl_sub bash run_mem.sh itemInfo_LIFG_DG.R
fsl_sub bash run_mem.sh itemInfo_LIFG_subiculum.R
fsl_sub bash run_mem.sh itemInfo_LIFG_ERC.R
fsl_sub bash run_mem.sh itemInfo_LIFG_HIP.R
fsl_sub bash run_mem.sh itemInfo_RIFG_CA1.R
fsl_sub bash run_mem.sh itemInfo_RIFG_CA2.R
fsl_sub bash run_mem.sh itemInfo_RIFG_CA3.R
fsl_sub bash run_mem.sh itemInfo_RIFG_DG.R
fsl_sub bash run_mem.sh itemInfo_RIFG_subiculum.R
fsl_sub bash run_mem.sh itemInfo_RIFG_ERC.R
fsl_sub bash run_mem.sh itemInfo_RIFG_HIP.R
